### ISSUE TITLE
How to train MinkUNet on SemanticKitti

### ISSUE THREAD

**Issue by DiegoWangSys** [mit-han-lab/e3d#1]
Thanks for your excellent work!
But how to train MinkUNet on semanticKitti dataset? I found the train and test results of MinkNet in your paper SPVNAS.

**Comment by kentangSJTU** [comment]
Hi,

Thanks for your interest in our work. We're still working on cleaning the training code, but you may refer to [this issue](https://github.com/mit-han-lab/torchsparse/issues/2) for how to perform training currently. 


Best,
Haotian

**Comment by kentangSJTU** [comment]
Training details for baseline models released [here](https://github.com/mit-han-lab/e3d/blob/master/spvnas/train.py).
