### ISSUE TITLE
There are not enough slots available in the system to satisfy the 8 slots

### ISSUE THREAD

**Issue by songyongkang** [mit-han-lab/e3d#10]
When I run:  
`torchpack dist-run -np 8 -v python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml`

the system tell me:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 8 slots 
that were requested by the application:
  python

Either request fewer slots for your application, or make more slots available
for use.

```

**Comment by kentangSJTU** [comment]
Hi,

You may not have enough GPUs on the machine. Therefore, please try `-np [num_gpus]` on your machine, thanks!

Best,
Haotian

**Comment by songyongkang** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:53:00.0 Off |                  N/A |
| 22%   28C    P8     3W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:54:00.0 Off |                  N/A |
| 22%   29C    P8     2W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:56:00.0 Off |                  N/A |
| 22%   30C    P8    18W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:57:00.0 Off |                  N/A |
| 22%   30C    P8    22W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:C1:00.0 Off |                  N/A |
| 22%   28C    P8    14W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:C2:00.0 Off |                  N/A |
| 22%   28C    P8    20W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:C4:00.0 Off |                  N/A |
| 22%   30C    P8    12W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:C5:00.0 Off |                  N/A |
| 22%   30C    P8     2W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by MEIXuYan** [comment]
Same question
```
$ torchpack dist-run -np 2 python train.py configs/semantic_kitti/minkunet/mink_dell.yaml
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 2 slots
that were requested by the application:
  python

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
```
nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:3B:00.0 Off |                  N/A |
| 19%   41C    P0    65W / 250W |      0MiB / 11019MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:5E:00.0 Off |                  N/A |
| 17%   37C    P0    64W / 250W |      0MiB / 11019MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:B1:00.0 Off |                  N/A |
| 14%   40C    P0    57W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:D9:00.0 Off |                  N/A |
| 11%   35C    P0    34W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by kentangSJTU** [comment]
Hi all,

I think the problem might be related to the `oversubscribe` flag of OpenMPI. To check whether it is the case, would you please try these two things on your machine?

- Will `-np 1` work for you?
- Please add `-v` to the `torchpack` command and copy the `mpiexec` command printed. Add the `-oversubscribe` flag to the printed command and see whether it works for you.

Thanks!

Best,
Haotian

**Comment by MEIXuYan** [comment]
Hi Haotian,
`-np 1` work for me, I got this with the `-v`command
```
╰─$ torchpack dist-run -np 2 -v python train.py configs/semantic_kitti/minkunet/mink_dell.yaml                                             1 ↵
mpirun --allow-run-as-root -np 2 -H localhost:2 -bind-to none -map-by slot -x AUTOJUMP_ERROR_PATH -x AUTOJUMP_SOURCED -x CXX -x EVENT_NOEPOLL -x HOME -x LANG -x LC_ADDRESS -x LC_IDENTIFICATION -x LC_MEASUREMENT -x LC_MONETARY -x LC_NAME -x LC_NUMERIC -x LC_PAPER -x LC_TELEPHONE -x LC_TERMINAL -x LC_TERMINAL_VERSION -x LC_TIME -x LD_LIBRARY_PATH -x LESS -x LOGNAME -x LSCOLORS -x LS_COLORS -x MAIL -x MASTER_HOST -x PAGER -x PATH -x PS1 -x PWD -x SHELL -x SHLVL -x SSH_CLIENT -x SSH_CONNECTION -x SSH_TTY -x TERM -x TMUX -x TMUX_PANE -x USER -x VIRTUAL_ENV -x XDG_RUNTIME_DIR -x XDG_SESSION_ID -x ZSH -x _ -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude docker0,lo python train.py configs/semantic_kitti/minkunet/mink_dell.yaml
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 2 slots
that were requested by the application:
  python

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
```
Can you show me how to add the output with` -oversubscribe`? I really know nothing about the openmpi. :(
By the way, how to set which GPUs to use with torchpack interface in a 4 GPUs machine？

Best,
Yan Xu

**Comment by kentangSJTU** [comment]
Hi Yan,

Sorry for the delayed response because I was working on an exam in the past two days. You should be adding this flag in the following way:

```bash
mpirun --allow-run-as-root -oversubscribe -np 2 -H localhost:2 -bind-to none -map-by slot -x AUTOJUMP_ERROR_PATH -x AUTOJUMP_SOURCED -x CXX -x EVENT_NOEPOLL -x HOME -x LANG -x LC_ADDRESS -x LC_IDENTIFICATION -x LC_MEASUREMENT -x LC_MONETARY -x LC_NAME -x LC_NUMERIC -x LC_PAPER -x LC_TELEPHONE -x LC_TERMINAL -x LC_TERMINAL_VERSION -x LC_TIME -x LD_LIBRARY_PATH -x LESS -x LOGNAME -x LSCOLORS -x LS_COLORS -x MAIL -x MASTER_HOST -x PAGER -x PATH -x PS1 -x PWD -x SHELL -x SHLVL -x SSH_CLIENT -x SSH_CONNECTION -x SSH_TTY -x TERM -x TMUX -x TMUX_PANE -x USER -x VIRTUAL_ENV -x XDG_RUNTIME_DIR -x XDG_SESSION_ID -x ZSH -x _ -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude docker0,lo python train.py configs/semantic_kitti/minkunet/mink_dell.yaml
```

Hope that works for you.



Best,
Haotian

**Comment by MEIXuYan** [comment]
Hi Haotian,
I found that I installed `mpich` package instead of `open-mpi` package, which is not perfectly suitable for `torchpack`, sorry.
I reinstall `openmpi`, `torchpack` and `mpi4py` using following shell commands, everything is fine now.

```bash
wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.5.tar.gz
gunzip -c openmpi-4.0.5.tar.gz | tar xf -
cd openmpi-4.0.5
./configure --prefix=/usr/local --with-orte
sudo make all -j8 install
pip install mpi4py
pip install --upgrade git+https://github.com/zhijian-liu/torchpack.git
```
Hope this can help someone with the same questions.

Best,
Yan Xu

**Comment by magic428** [comment]
#

> Hi Haotian,
> I found that I installed `mpich` package instead of `open-mpi` package, which is not perfectly suitable for `torchpack`, sorry.
> I reinstall `openmpi`, `torchpack` and `mpi4py` using following shell commands, everything is fine now.
> 
> ```shell
> wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.5.tar.gz
> gunzip -c openmpi-4.0.5.tar.gz | tar xf -
> cd openmpi-4.0.5
> ./configure --prefix=/usr/local --with-orte
> sudo make all -j8 install
> sudo ldconfig
> pip install mpi4py
> pip install --upgrade git+https://github.com/zhijian-liu/torchpack.git
> ```
> 
> Hope this can help someone with the same questions.
> 
> Best,
> Yan Xu

Hi Yan Xu, 
I met the same problem and I do as you mentioned above, and It didn't work.

Best, 
Gorzhij

**Comment by MEIXuYan** [comment]
> > Hi Haotian,
> > I found that I installed `mpich` package instead of `open-mpi` package, which is not perfectly suitable for `torchpack`, sorry.
> > I reinstall `openmpi`, `torchpack` and `mpi4py` using following shell commands, everything is fine now.
> > ```shell
> > wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.5.tar.gz
> > gunzip -c openmpi-4.0.5.tar.gz | tar xf -
> > cd openmpi-4.0.5
> > ./configure --prefix=/usr/local --with-orte
> > sudo make all -j8 install
> > sudo ldconfig
> > pip install mpi4py
> > pip install --upgrade git+https://github.com/zhijian-liu/torchpack.git
> > ```
> > 
> > 
> > Hope this can help someone with the same questions.
> > Best,
> > Yan Xu
> 
> Hi Yan Xu,
> I met the same problem and I do as you mentioned above, and It didn't work.
> 
> Best,
> Gorzhij

Maybe you can try `sudo rm -rf ~/.cache/pip` to remove the pip cache, then redo the above pip install commands.
