### ISSUE TITLE
ImportError: libtorch.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by feifeiwei** [mit-han-lab/e3d#18]

**Comment by feifeiwei** [comment]
Hi, i got this error when i run 'torchpack dist-run -np 1 python evaluate.py configs/semantic_kitti/default.yaml --name SemanticKITTI_val_SPVNAS@65GMACs'
i want to know how to fix it please

**Comment by kentangSJTU** [comment]
Hello,

I haven't met with this problem before, so I can only try to solve it with you together. Would you mind helping me confirm the following things?

- Did you met with similar problem other PyTorch programs?
- Have you successfully installed the torchsparse library?
- Did you have multiple CUDA environments on your computer?

Thanks,
Haotian

**Comment by zhijian-liu** [comment]
I will close the issue for now due to the inactivity. Feel free to reopen the issue if needed.
