### ISSUE TITLE
Question about the difference between PVCNN and SPVCNN

### ISSUE THREAD

**Issue by jialeli1** [mit-han-lab/e3d#19]
Awesome performance! 

If the NAS part is excluded, is it just that the sparse 3D convolution is added to SPVCNN, compared to PVCNN? However, I thought you already used the sparse 3D convolution in PVCNN when I read PVCNN some time ago. After all, you have already cited the sparse 3D convolution and SECOND in PVCNN.

If the answer is yes, I feel very regret that I missed this idea.

**Comment by kentangSJTU** [comment]
Hello,

We actually didn't use sparse 3D convolution in PVCNN. 


Best,
Haotian

**Comment by chaitjo** [comment]
Hi @kentangSJTU, I had a quick follow-up on this discussion:  
> the voxelization / devoxelization operations are more challenging, therefore we don't want to have too many SPVConv layers

Do you mean that the voxelization/devoxelization operations for sparse tensors are more time costly in the SPVConv layers compared to PVConv (i.e. dense 3D convolution)? Any further insight would be very helpful.

**Comment by kentangSJTU** [comment]
Hi @chaitjo, 

Thanks for your interest. For dense tensors, we can directly infer a point's memory location given its coordinates (coordinate x,y,z will correspond to memory location x * y_max * z_max + y * z_max + z). However, for sparse tensors, there is no such property, and we have to rely on hash map query to obtain the memory location of a point given its coordinates. Therefore, voxelization and devoxelization operations can be slower.

Best,
Haotian

**Comment by chaitjo** [comment]
Thanks for the explanation!
