### ISSUE TITLE
Is there any other rerequisites or settings before running "torchpack dist-run..." ?

### ISSUE THREAD

**Issue by Woodpecker0** [mit-han-lab/e3d#2]
**Thanks for your wonderful work! The model works fine even on velodyne vlp16 dataset.** 

  But when I try to test pretrained models with "torchpack dist-run...", some errors come up:

`**$ torchpack dist-run -np 1 python train.py configs/semantic_kitti/spvcnn/cr0$p5.yaml**

ssh: Could not resolve hostname localhost:1: Name or service not known
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------`

 Since I have install all the rerequisites according to README.md, I have no idea what may cause this problem. Is there any other rerequisites or settings ?

**Comment by Woodpecker0** [comment]
I solve this problem by adding '127.0.0.1  localhost:1' to /etc/hosts.

**Comment by DiegoWangSys** [comment]
Dear Woodpecker0:
what if I could not edit /etc/hosts and how I append the  '127.0.0.1 localhost:1' to /etc/hosts.
:)
Best!

**Comment by DiegoWangSys** [comment]
I changed the code into single GPU version (without distributed training) and fix the issue

**Comment by isunLt** [comment]
> I changed the code into single GPU version (without distributed training) and fix the issue

Hi, I just met the same problem as you and I cannot edit /etc/hosts either. I finally solve the problem without modifying the code.
I find that the common reason to cause this problem `Could not resolve hostname xxxxx: Name or service not known` is that there exists multiple version of `openmpi` in the system. You might use an older verison to compile `mpi4py` and `torchpack`. You could use the command `mpirun --version` to see which version of openmpi you are using and then modify the default `mpirun` path by `export PATH="<where/the/newer/mpirun/is>:$PATH"`. Finally, reinstall `mpi4py` and `torchpack` and remember not to use the cached `mpi4py` and `torchpack` packages.
Hope this will work for you. More details can be find [there](https://github.com/horovod/horovod/issues/1032).
