### ISSUE TITLE
Question about the implementation details of SECOND(our)

### ISSUE THREAD

**Issue by jialeli1** [mit-han-lab/e3d#20]
There is only one sentence about the realization of **SECOND (ours)** on page 12 of the article:
"As for our model, we only replace these 3D Sparse Convolutions in SECOND with our SPVConv while keeping all the other settings the same for fair comparison. "

However, when I think carefully, there are some unclear points.  In SPVCNN (and PVCNN), the neighborhood information is collected by the Voxel branch, and then it flows to the Point branch. The final feature representation is on the Point branch. On the contrary, the final feature representation in SECOND is on the structured feature map from the Voxel branch.  So, I am interested in how you “only replace these 3D Sparse Convolutions in SECOND with our SPVConv ” ？

Looking forward to your reply.

**Comment by kentangSJTU** [comment]
Hello,

I think you can refer to #13 for some detection-related discussions. 

Best,
Haotian
