### ISSUE TITLE
# of MACs in paper

### ISSUE THREAD

**Issue by fhartmann17** [mit-han-lab/e3d#22]
Hi,

congrats to this awesome work and thanks for releasing your code.
I have a question regarding tables 2 and 3 in the paper.

How did you calculate the number of MACs? (also for the other approaches) 

Thanks!

**Comment by kentangSJTU** [comment]
Hello,

Please refer to [this issue](https://github.com/mit-han-lab/torchsparse/issues/9).

Best,
Haotian

**Comment by kentangSJTU** [comment]
Hello,

The overall idea of calculating SparseConv MACs is the same. However, actually we pre-calculate the average kernel map sizes for each scene instead of using `thop` to measure the MACs for all the scenes (which will take too long time if done on the fly).

Best,
Haotian
