### ISSUE TITLE
Questions About core/datasets/semantic_kitti.py

### ISSUE THREAD

**Issue by RS-Coop** [mit-han-lab/e3d#25]
Hello, I have a couple of questions about some of the data processing in the dataset file "core/datasets/semantic_kitti.py". I have been using that as a bit of a reference in trying to do something similar with the nuScenes dataset.

1. The output SparseTensors from __getitem__ are created from NumPy arrays which has caused me some problems in trying to run inference with SPVNAS. It seems the issue potentially stems from a few places (e.g. converting to cuda). I have fixed this by converting to torch tensors before creating the SparseTensors, and this seems like a perfectly fine solution, but mostly I am curious why this is not done in your code? I couldn't seem to find another place where it would have been handled. A similar thing appears to be going on in the example for the torchsparse library also.

2. It seems to me that the features for a voxel should be the mean coordinate of the points contained in that voxel and the mean lidar intensity of those points. However, it appears as if you are taking a voxel feature to be the feature for only one of the points in that voxel. Is this correct, or am I misunderstanding something?

3. In terms of point cloud pre-processing it seems you are subtracting the minimum of each coordinate. Is this all that is done, it seems to me that some more normalization would be helpful.

4. Is the labels variable returned by sparse_quantize the same as the input labels parameter, and if so what is the purpose of this?

Thanks for all the help!

**Comment by kentangSJTU** [comment]
Hello,

Thanks for your interest!

1. This is actually done in the collate function of the dataset. I'll consider to move the torch Tensor construction to the dataset file in the future such that users will feel less confused.

2. Yes, your understanding is correct. I think using the mean coordinate within the grid will be an interesting direction to explore but we haven't tried.

3. Normalization is not needed here since we will perform some sparse 3d convolution instead of volumetric convolution. By the way, subtracting the min value is also unnecessary now.

4. In most cases no. Following the design of MinkowskiEngine, we set the label of a grid to 255 if there's multiple points with conflicting labels in it.

Hope that these answers can resolve your question.

Best,
Haotian

**Comment by RS-Coop** [comment]
Haotian, 

Thanks for the quick response and I really appreciate your help!

I had one other quick question which is about the dimensionality of the coordinates being used in SparseTensors. These coordinates are four dimensional, but I dont understand what that fourth dimension is for. In raw LiDAR data this is the intensity, but when we are taking about the coordinates of a point don't we just need xyz values?

Thanks again

**Comment by RS-Coop** [comment]
Also I wasn't sure if you would see my above comment without me doing this: @kentangSJTU

**Comment by zhijian-liu** [comment]
In the SparseTensor representation, the coordinates are four dimensions as the first three are x, y, and z, and the last one is the batch index. When we organize a batch of point clouds, we will concatenate all the coordinates together and add one more dimension to differentiate between different instances.

**Comment by RS-Coop** [comment]
@zhijian-liu Okay I understand, so in the dataset you're just leaving what was the intensity dimension and then overwriting it with the batch.

**Comment by RS-Coop** [comment]
@zhijian-liu Thanks for answering all my questions and thanks for all the great work you have done. If you don't mind bearing with me I have just one more. Is there a mapping from the 19 class labels you keep to their associated names? It seems like you are doing this programatically in the dataset.

Thanks!

**Comment by zhijian-liu** [comment]
Please refer to https://github.com/mit-han-lab/e3d/blob/master/spvnas/core/datasets/semantic_kitti.py#L59.

**Comment by RS-Coop** [comment]
Do the indices of that list map to the output of the network?

**Comment by zhijian-liu** [comment]
I see what you are asking. The mapping you are looking for is at https://github.com/mit-han-lab/e3d/blob/master/spvnas/visualize.py#L88-L94.

**Comment by RS-Coop** [comment]
Perfect! Thanks for all your help!

**Comment by zbl-96** [comment]
@zhijian-liu  hello,i also have  a question for data processing. In your paper i found you say coordinates normalization,but I did not find this operation.As I understand it, normalizationis also needed, right?

**Comment by zbl-96** [comment]
> @zhijian-liu hello,i also have a question for data processing. In your paper i found you say coordinates normalization,but I did not find this operation.As I understand it, normalizationis also needed, right?

@kentangSJTU  can you help me?

**Comment by zhijian-liu** [comment]
Please refer to https://github.com/mit-han-lab/spvnas/blob/master/core/datasets/semantic_kitti.py#L197-L198 for more details.

**Comment by zbl-96** [comment]
> Please refer to https://github.com/mit-han-lab/spvnas/blob/master/core/datasets/semantic_kitti.py#L197-L198 for more details.
Thank you for your reply.
Yes,I noticed this code.
I think that for scenes of different sizes, there is still a big difference in the value of the edge of the scene.

**Comment by zbl-96** [comment]
> Please refer to https://github.com/mit-han-lab/spvnas/blob/master/core/datasets/semantic_kitti.py#L197-L198 for more details.

Thank you for your reply.
Yes,I noticed this code.
I think that for scenes of different sizes, there is still a big difference in the value of the edge of the scene.

**Comment by zhijian-liu** [comment]
I'm not sure what you mean by "the edge of the scene". Is it the range/scale of the scene? If so, then yes, the range/scale of the scene may still vary a lot, and we do not do extra normalization to rescale the scene.

**Comment by zbl-96** [comment]
English is not my native language.right,"range/scale of the scene"  is what i mean.I'm thinking about this matter, anyway thank you for your reply
