### ISSUE TITLE
Provide full list of requirements

### ISSUE THREAD

**Issue by ltriess** [mit-han-lab/e3d#26]
The installation process would be a lot faster if the repo had a `requirements.txt` or `setup.py`. Especially since the prerequisites listed here https://github.com/mit-han-lab/e3d#prerequisites are not complete. For example `spvnas/core/datasets/semantic_kitti.py` also requires `h5py`, `numba`, `opencv-python`.

**Comment by kentangSJTU** [comment]
Hello,

Sorry about the inconvenience and thanks a lot for the great suggestion! I will try it soon. 

Best,
Haotian
