### ISSUE TITLE
Transfer the learnings from the pretrained models to training in custom datasets.

### ISSUE THREAD

**Issue by sandeepnmenon** [mit-han-lab/e3d#29]
Does the repo support training on new dataset after preloading the model with given weights and editing some layers of the architecture?

Thank you

**Comment by zhijian-liu** [comment]
It currently does not support this. We are planning to release a new version of the codebase soon to support training with more datasets. Stay tuned!

**Comment by ezgicakirofficial** [comment]
Hello, is there any update regarding this? Is transfer learning possible now?
