### ISSUE TITLE
ROS inference node and visualization in RVIZ

### ISSUE THREAD

**Issue by YoushaaMurhij** [mit-han-lab/e3d#3]
Thanks for your interesting work!. Adding a ROS node to visualize results in RVIZ would be great?

**Comment by kentangSJTU** [comment]
Hi,

Thanks for the idea! I'm personally not very familiar with ROS and RVIZ, it will be great if someone interested can add this feature to our codebase. 

Best,
Haotian

**Comment by YoushaaMurhij** [comment]
Ok! Could you please provide some information about **.label** file that you used in visualise.py file? this will help a lot!

**Comment by kentangSJTU** [comment]
Hi,

I've updated the visualization code such that it can work if label file is not given. Please have a try, thanks!

Best,
Haotian
