### ISSUE TITLE
ssh: Could not resolve hostname localhost:1: Temporary failure in name resolution

### ISSUE THREAD

**Issue by LuwooChen** [mit-han-lab/e3d#30]
When I run "torchpack dist-run -np 1 python train.py configs/semantic_kitti/spvcnn/default.yaml" on a ubuntu server, I met this error:
"ssh: Could not resolve hostname localhost:1: Temporary failure in name resolution". Additionally, I'm not root user.
Does anybody know how to solve that?

**Comment by zhijian-liu** [comment]
Hi, could you please try `torchpack dist-run -np 1 -H 127.0.0.1:1 python train.py configs/semantic_kitti/spvcnn/default.yaml` instead?

**Comment by zhijian-liu** [comment]
I'm closing this issue due to the inactivity. Please feel free to reopen it if the problem is not resolved.
