### ISSUE TITLE
/bin/sh: 1: mpirun: not found

### ISSUE THREAD

**Issue by sjtuchenye** [mit-han-lab/e3d#31]
How should I deal with this error '/bin/sh: 1: mpirun: not found' when I run ''torchpack dist-run -np 1 python train.py configs/semantic_kitti/spvcnn/default.yaml"

**Comment by zhijian-liu** [comment]
I think you might need to first install `openmpi`.

**Comment by zhijian-liu** [comment]
I'm closing this issue due to the inactivity. Please feel free to reopen it if the problem is not resolved.

**Comment by Gofinge** [comment]
I tried to run the code on an ubuntu 16 server. At first, I try to install opemmpi var "apt", but the default version of mpirun is 1.0x. I built openmpl 4.0 version manually, and it solved the problem.
