### ISSUE TITLE
Error when importing SPVNAS model to run inference 

### ISSUE THREAD

**Issue by fredpeertje** [mit-han-lab/e3d#38]
I use the e3d.ipynb from the tutorial folder. I get the following error when importing SPVNAS model to run inference:
`model = spvnas_specialized('SemanticKITTI_val_SPVNAS@65GMACs').to(device)`
`RuntimeError: running_mean should contain 1000 elements not 44`

Also, when will the training code for SPVNAS be available?

**Comment by ken748322** [comment]
I ran into same problem.
I used `torchspares tag v1.0.0` to avoid this problem.
Use `pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.0.0` instead of `pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git `

**Comment by fredpeertje** [comment]
Hmm thanks for providing this info!
I'm curious what recent change of torchsparse caused this issue @zhijian-liu
