### ISSUE TITLE
Which label belongs to which semanticKITTI IOU prediction

### ISSUE THREAD

**Issue by fredpeertje** [mit-han-lab/e3d#44]
I can't figure out which label belongs to which IOU prediction when evaluating on the semanticKITTI dataset. 

The file semantic_kitti.py defines the following list: 
```
kept_labels = [
    'road', 'sidewalk', 'parking', 'other-ground', 'building', 'car', 'truck',
    'bicycle', 'motorcycle', 'other-vehicle', 'vegetation', 'trunk', 'terrain',
    'person', 'bicyclist', 'motorcyclist', 'fence', 'pole', 'traffic-sign'
]
```

I run the following command:
`!torchpack dist-run -np 1 python evaluate.py configs/semantic_kitti/default.yaml --name SemanticKITTI_val_SPVNAS@65GMACs`

And get the following IOU prediction output:
```[0.9718420082206927, 0.38961800341472447, 0.7145743531211676, 0.6846713350897515, 0.6445271805914676, 0.7246225795083294, 0.8675636397731001, 0.0012132890839667415, 0.9343194385183315, 0.5199240494364405, 0.812111782522395, 0.0001901425259827739, 0.9177672828390993, 0.6610816523276035, 0.8819792946476588, 0.6617228983717633, 0.7466429908103505, 0.6438834155400621, 0.5139405980831536]```

Where in the code is the order of the labels defined, used for printing the IOU predictions?

**Comment by zhijian-liu** [comment]
The mapping you are looking for is at https://github.com/mit-han-lab/e3d/blob/master/spvnas/visualize.py#L88-L94.
