### ISSUE TITLE
Values to unpack

### ISSUE THREAD

**Issue by maxim0815** [mit-han-lab/e3d#8]
Hey,

nice work. The results for the SemanticKITTI datasets are looking very promising.
I wanted to play around with your network approach and faced the problem:
"not enough values to unpack (expected 2, got 1)" during the forward pass of the class SPVCNN. I tried the mentioned [example](https://github.com/mit-han-lab/torchsparse/blob/aec536ec0ed8813569399e2422c7f5f3ac1eb773/examples/example.py) within the subrepo and got the same problem.

Thanks.

**Comment by kentangSJTU** [comment]
Hello,

Would you mind posting the entire error log here so that I can help you debug the code together? I haven't meet with such problem when testing with the example after installing the latest torchsparse. Thanks!


Best,
Haotian

**Comment by vassilybar** [comment]
I encountered same issue when running on cpu. As I understood, that happens because there is no cpu version for `torchsparse_cuda.count_forward()`. So it returns normal values when running on gpu and zeros on cpu.

**Comment by maxim0815** [comment]
The entire error log for the torchsparse example is:
![image](https://user-images.githubusercontent.com/57002046/94792461-4c6e0f80-03d9-11eb-8edb-1ca8e1c6ae18.png)

I printed the selected device to make sure its running on gpu. But also running on cpu the example crashes. But not with the same issue @vassilybar mentioned. Instead following runtime error shows up:
![image](https://user-images.githubusercontent.com/57002046/94793122-462c6300-03da-11eb-9c21-431ec2e81da7.png)

I'm running Ubuntu 18.04.5 LTS
Python 3.6.9
Pytorch 1.6
Cuda 10.2

**Comment by vassilybar** [comment]
Here is what happens when I try to make predictions with SemanticKITTI_val_SPVNAS@65GMACs like in the tutorial:
On cuda:
![image](https://user-images.githubusercontent.com/36568619/94798558-fa92ad00-040b-11eb-99b1-2ce7e8751226.png)
On cpu:
![image](https://user-images.githubusercontent.com/36568619/94798625-1302c780-040c-11eb-93f7-588017a7fb35.png)
And the resulting error on cpu:
![image](https://user-images.githubusercontent.com/36568619/94798691-29108800-040c-11eb-9275-dc9616ccdcf0.png)

Python 3.6.3
Pytorch 1.6
Cuda 10.1

**Comment by kentangSJTU** [comment]
Hi all,

Thanks a lot for the reporting this bug. The bug related to `torchsparse` and I'm currently working hard to fix it. I'll come back to this thread as soon as possible.

Best,
Haotian

**Comment by Xiangxu-0103** [comment]
Hi, I have met the same problem with you. Have you solved the problem now? @maxim0815

**Comment by maxim0815** [comment]
Since I need a working cpu version I was waiting for @kentangSJTU . But as he mentioned the gpu version should work.

**Comment by kentangSJTU** [comment]
Hi,

Please install the latest `torchsparse` and check whether the problem still exists. I have updated the CPU version about a month ago.

Best,
Haotian

**Comment by Xiangxu-0103** [comment]
Hi,
   I reinstall the CUDA version with 10.2 and the problem has been solved.   Thanks for your help.
